codecov:
  token: 6d6a8b66-d336-4dc8-b013-01b62675dbad
  max_report_age: 1
  require_ci_to_pass: false

comment:
  behavior: default
  layout: reach, diff, flags, files
  require_changes:
    - 0

coverage:
  precision: 2
  range:
    - 50.0
    - 100.0
  round: down
  status:
    patch:
      default:
        informational: true
        target: auto
        threshold: 5.0
    project:
      default:
        informational: true
        target: auto
        threshold: 5.0

ignore:
  - (?s:tests/.*)\Z
  - (?s:docs/.*)\Z
  - (?s:.*/build/.*)\Z
  - (?s:.*/_deps/.*)\Z
  - name: Upload test results to Codecov
  if: ${{ !cancelled() }}
  uses: codecov/test-results-action@v1
  with:
    token: ${{ secrets.CODECOV_TOKEN }}
